// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wksitdwpynvnvpfytexu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indrc2l0ZHdweW52bnZwZnl0ZXh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMjAyNjUsImV4cCI6MjA2NTU5NjI2NX0.PrBFunqxuS5inIr3Qhq4u0TFbyzVIyylCyBe9N8Ah8M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);